# Generated by Django 6.0.1 on 2026-03-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_accessory_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('suv', 'SUV'), ('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('muv', 'MUV'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('van', 'Van'), ('jeep', 'Jeep')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='boot_space',
            field=models.PositiveIntegerField(blank=True, help_text='Boot space in Liters', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_displacement',
            field=models.PositiveIntegerField(blank=True, help_text='Engine displacement in cc', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_tank_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Fuel tank capacity in Liters', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='has_abs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='has_airbags',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='has_sunroof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='max_power',
            field=models.CharField(blank=True, help_text='e.g., 113.18 bhp @ 4000 rpm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='max_torque',
            field=models.CharField(blank=True, help_text='e.g., 250 Nm @ 1500-2750 rpm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='seating_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Number of seats', null=True),
        ),
    ]
