# Generated by Django 6.0.1 on 2026-03-26 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_carimage_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='compatible_car',
        ),
        migrations.AddField(
            model_name='accessory',
            name='category',
            field=models.CharField(choices=[('Interior', 'Interior'), ('Exterior', 'Exterior'), ('Safety', 'Safety'), ('Comfort', 'Comfort'), ('Tech', 'Tech')], default='Interior', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='cars', to='vehicles.accessory'),
        ),
        migrations.CreateModel(
            name='FavoriteAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vehicles.accessory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_accessories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'accessory')},
            },
        ),
    ]
