# Generated by Django 6.0.1 on 2026-03-26 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('gu', 'Gujarati')], default='en', max_length=5),
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text='Browser/OS string', max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_login'],
                'unique_together': {('user', 'device_name', 'ip_address')},
            },
        ),
    ]
