# Generated by Django 6.0.1 on 2026-03-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_car_body_type_car_boot_space_car_engine_displacement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.AddField(
            model_name='car',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum price in INR', max_digits=12),
        ),
        migrations.AddField(
            model_name='car',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum price in INR', max_digits=12),
        ),
    ]
