# Generated by Django 6.0.1 on 2026-03-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='category',
            field=models.CharField(choices=[('exterior', 'Exterior'), ('interior', 'Interior'), ('colors', 'Colors'), ('360_view', '360° View')], default='exterior', max_length=20),
        ),
    ]
