# Generated by Django 6.0.1 on 2026-03-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_carenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cars', models.ManyToManyField(related_name='comparison_events', to='vehicles.car')),
            ],
            options={
                'verbose_name': 'Comparison',
                'verbose_name_plural': 'Comparisons',
                'ordering': ['-created_at'],
            },
        ),
    ]
