import os
import sys
import django
from decimal import Decimal

# Set up Django
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'vehiclevault.settings')
django.setup()

from vehicles.models import Car

def add_mock_cars():
    cars_data = [
        {
            "make": "Maruti Suzuki",
            "model": "Swift",
            "year": 2024,
            "min_price": Decimal("5.99"),
            "max_price": Decimal("9.03"),
            "mileage": "22.38 kmpl",
            "engine": "petrol",
            "transmission": "manual",
            "safety_rating": "2",
            "description": "A popular, sporty hatchback known for its peppy engine and agility.",
            "body_type": "hatchback",
            "engine_displacement": 1197,
            "max_power": "88.50 bhp @ 6000 rpm",
            "max_torque": "113 Nm @ 4400 rpm",
            "fuel_tank_capacity": 37,
            "seating_capacity": 5,
            "boot_space": 268,
            "has_abs": True,
            "has_airbags": True,
            "has_sunroof": False
        },
        {
            "make": "Hyundai",
            "model": "Creta",
            "year": 2024,
            "min_price": Decimal("10.99"),
            "max_price": Decimal("20.14"),
            "mileage": "17.4 kmpl",
            "engine": "petrol",
            "transmission": "automatic",
            "safety_rating": "3",
            "description": "India's favorite compact SUV offering a feature-rich, comfortable ride.",
            "body_type": "suv",
            "engine_displacement": 1497,
            "max_power": "113.18 bhp @ 6300 rpm",
            "max_torque": "143.8 Nm @ 4500 rpm",
            "fuel_tank_capacity": 50,
            "seating_capacity": 5,
            "boot_space": 433,
            "has_abs": True,
            "has_airbags": True,
            "has_sunroof": True
        },
        {
            "make": "Mahindra",
            "model": "Thar",
            "year": 2024,
            "min_price": Decimal("11.25"),
            "max_price": Decimal("17.60"),
            "mileage": "15.2 kmpl",
            "engine": "diesel",
            "transmission": "manual",
            "safety_rating": "4",
            "description": "An iconic off-roader blending rugged capability with modern creature comforts.",
            "body_type": "suv",
            "engine_displacement": 2184,
            "max_power": "130.07 bhp @ 3750 rpm",
            "max_torque": "300 Nm @ 1600-2800 rpm",
            "fuel_tank_capacity": 57,
            "seating_capacity": 4,
            "boot_space": 0,
            "has_abs": True,
            "has_airbags": True,
            "has_sunroof": False
        },
        {
            "make": "Kia",
            "model": "Seltos",
            "year": 2024,
            "min_price": Decimal("10.89"),
            "max_price": Decimal("20.34"),
            "mileage": "17.0 kmpl",
            "engine": "petrol",
            "transmission": "automatic",
            "safety_rating": "3",
            "description": "A stylish and dynamic SUV offering cutting-edge technology and bold design.",
            "body_type": "suv",
            "engine_displacement": 1497,
            "max_power": "113.43 bhp @ 6300 rpm",
            "max_torque": "144 Nm @ 4500 rpm",
            "fuel_tank_capacity": 50,
            "seating_capacity": 5,
            "boot_space": 433,
            "has_abs": True,
            "has_airbags": True,
            "has_sunroof": True
        },
        {
            "make": "Tata",
            "model": "Nexon",
            "year": 2024,
            "min_price": Decimal("8.15"),
            "max_price": Decimal("15.59"),
            "mileage": "17.33 kmpl",
            "engine": "petrol",
            "transmission": "manual",
            "safety_rating": "5",
            "description": "A 5-star safety rated compact SUV with striking looks and a spacious cabin.",
            "body_type": "suv",
            "engine_displacement": 1199,
            "max_power": "118.27 bhp @ 5500 rpm",
            "max_torque": "170 Nm @ 1750-4000 rpm",
            "fuel_tank_capacity": 44,
            "seating_capacity": 5,
            "boot_space": 382,
            "has_abs": True,
            "has_airbags": True,
            "has_sunroof": True
        },
        {
            "make": "Toyota",
            "model": "Innova Crysta",
            "year": 2024,
            "min_price": Decimal("19.99"),
            "max_price": Decimal("26.30"),
            "mileage": "14.0 kmpl",
            "engine": "diesel",
            "transmission": "manual",
            "safety_rating": "4",
            "description": "India's undisputed king of MPVs, renowned for its bulletproof reliability and unmatched comfort.",
            "body_type": "muv",
            "engine_displacement": 2393,
            "max_power": "147.51 bhp @ 3400 rpm",
            "max_torque": "343 Nm @ 1400-2800 rpm",
            "fuel_tank_capacity": 65,
            "seating_capacity": 7,
            "boot_space": 300,
            "has_abs": True,
            "has_airbags": True,
            "has_sunroof": False
        },
        {
            "make": "Honda",
            "model": "City",
            "year": 2024,
            "min_price": Decimal("11.70"),
            "max_price": Decimal("16.25"),
            "mileage": "17.8 kmpl",
            "engine": "petrol",
            "transmission": "automatic",
            "safety_rating": "5",
            "description": "The quintessential executive sedan boasting elegant design, supreme comfort, and a rev-happy engine.",
            "body_type": "sedan",
            "engine_displacement": 1498,
            "max_power": "119.35 bhp @ 6600 rpm",
            "max_torque": "145 Nm @ 4300 rpm",
            "fuel_tank_capacity": 40,
            "seating_capacity": 5,
            "boot_space": 506,
            "has_abs": True,
            "has_airbags": True,
            "has_sunroof": True
        },
        {
            "make": "Volkswagen",
            "model": "Virtus",
            "year": 2024,
            "min_price": Decimal("11.55"),
            "max_price": Decimal("19.40"),
            "mileage": "19.40 kmpl",
            "engine": "petrol",
            "transmission": "automatic",
            "safety_rating": "5",
            "description": "A thrilling premium sedan offering German engineering, exceptional driving dynamics, and top-tier safety.",
            "body_type": "sedan",
            "engine_displacement": 999,
            "max_power": "113.98 bhp @ 5000-5500 rpm",
            "max_torque": "178 Nm @ 1750-4500 rpm",
            "fuel_tank_capacity": 45,
            "seating_capacity": 5,
            "boot_space": 521,
            "has_abs": True,
            "has_airbags": True,
            "has_sunroof": True
        },
        {
            "make": "MG",
            "model": "Hector",
            "year": 2024,
            "min_price": Decimal("14.72"),
            "max_price": Decimal("22.11"),
            "mileage": "15.58 kmpl",
            "engine": "diesel",
            "transmission": "manual",
            "safety_rating": "5",
            "description": "India's first internet car, delivering a massive footprint, vast interior space, and a gigantic touchscreen.",
            "body_type": "suv",
            "engine_displacement": 1956,
            "max_power": "167.67 bhp @ 3750 rpm",
            "max_torque": "350 Nm @ 1750-2500 rpm",
            "fuel_tank_capacity": 60,
            "seating_capacity": 5,
            "boot_space": 587,
            "has_abs": True,
            "has_airbags": True,
            "has_sunroof": True
        },
        {
            "make": "Maruti Suzuki",
            "model": "Baleno",
            "year": 2024,
            "min_price": Decimal("6.66"),
            "max_price": Decimal("9.88"),
            "mileage": "22.35 kmpl",
            "engine": "petrol",
            "transmission": "manual",
            "safety_rating": "0",
            "description": "A spacious, feature-loaded premium hatchback that promises excellent fuel efficiency and low maintenance.",
            "body_type": "hatchback",
            "engine_displacement": 1197,
            "max_power": "88.50 bhp @ 6000 rpm",
            "max_torque": "113 Nm @ 4400 rpm",
            "fuel_tank_capacity": 37,
            "seating_capacity": 5,
            "boot_space": 318,
            "has_abs": True,
            "has_airbags": True,
            "has_sunroof": False
        }
    ]

    print("Adding 10 mock cars without images into the database...")
    for data in cars_data:
        Car.objects.create(**data)
        print(f"Created: {data['make']} {data['model']}")

    print("\nSuccessfully added 10 cars!")

if __name__ == '__main__':
    add_mock_cars()
